### ISSUE TITLE
Tokio 0.2 (async/await)

### ISSUE THREAD

**Issue by frol** [rsocket/rsocket-rust#1]
Do you have plans to migrate to async/await syntax?

**Comment by jjeffcaii** [comment]
Yes! I think that `async/await` is the best way to implement it, but there is still a lot of work to do for this repo before it.
I'm a beginner of Rust. Welcome to contribute codes if you are interested. :smiley:

**Comment by jjeffcaii** [comment]
`async/await` has been added in release v0.2.0. @frol
