### ISSUE TITLE
question: request stream and channel for wasm-transport

### ISSUE THREAD

**Issue by kuronyago** [rsocket/rsocket-rust#12]
I want to implement the remaining methods for wasm transport, but I got stuck almost at the beginning

**Comment by kuronyago** [comment]
for example request stream

essentially I need to return the same Future, but with the Output = Stream type?

**Comment by jjeffcaii** [comment]
In current implementation, if you want to use RequestStream/RequestChannel, you had to use native rust code. (see here: [https://github.com/jjeffcaii/rsocket-rust-wasm-example/blob/master/src/lib.rs](https://github.com/jjeffcaii/rsocket-rust-wasm-example/blob/master/src/lib.rs))
Well, it's not graceful and `JsClient` is not ready for stream. 😭 
For RequestResponse, we can use `Promise` to wrap, but I don't known how to wrap stream payload(maybe use callback `Fn`). So you need to find best way to wrap stream before starting it. 😃 

The community is open, welcome to join us! 😄
