### ISSUE TITLE
Upgrade to Tokio 1.0

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket-rust#33]
Migrated to Tokio 1.0 and bytes 1.0

**Comment by jjeffcaii** [comment]
I started the migration a few days ago, but the `tokio-tungstenite` which the websocket transport based on doesn't support it. Today I found the [tokio-v1 PR](https://github.com/snapview/tokio-tungstenite/pull/142) has been merged, I'll complete the rest work in the next few days.

Thanks!

**Comment by jjeffcaii** [comment]
Migration is completed, and it will be released with `v0.7.0` in the next few days.

Thanks!
