### ISSUE TITLE
Add rsocket-rust to the implementing libraries on the official website

### ISSUE THREAD

**Issue by AntonOellerer** [rsocket/rsocket-rust#53]
Hey,
Are there any reasons why this library is not listed in the official list on the [rsocket website](https://rsocket.io/about/implementations/)?
Best regards
Anton

**Comment by jjeffcaii** [comment]
Thanks for reporting. I've added an PR for rsocket-website, https://github.com/rsocket/rsocket-website/pull/69.

**Comment by jjeffcaii** [comment]
The PR has been merged, and it's listed on the website now.
