### ISSUE TITLE
How to handle the client actively closing the connection ？

### ISSUE THREAD

**Issue by panicfrog** [rsocket/rsocket-rust#58]
How to handle the client actively closing the connection ？

**Comment by jjeffcaii** [comment]
You can call `on_close`  when building the client.

**Comment by panicfrog** [comment]
> You can call `on_close` when building the client.

Thank you for your answer, what I want to know is how does the server know that the client is disconnected. And I still have some questions. First, how does the server actively disconnect from a specific client? Second, how to use authorization?

**Comment by jjeffcaii** [comment]
Currently, we have no method to handle client disconnection or actively disconnect from an established client, and these features will be added into my to-do list.
For the second, you can use `SetupPayload` to verify incoming client connections, for example:
```rust
    RSocketFactory::receive()
        .transport(transport)
        .acceptor(Box::new(|setup, _socket| {
            info!("accept setup: {:?}", setup);
            Ok(Box::new(EchoRSocket))
            // Or you can check the setup, and reject setup
            // Err(From::from("NOT_AUTHORIZATION"))
        }))
        .serve()
        .await
```
