### ISSUE TITLE
Closure support for server acceptor

### ISSUE THREAD

**Issue by derekam** [rsocket/rsocket-rust#7]
Currently the acceptor setup for the server takes a function pointer (FnAcceptorWithSetup)/doesn't take closures, so there's no way to create and pass a dynamic/configurable acceptor. I have it modified for this locally (basically fn -> Fn and boxing it). I see you've made similar changes to the server's startup function, so is this something you already have underway/have a plan for or can I open a PR?

**Comment by jjeffcaii** [comment]
Yes! I'm planing to release v0.5.1 when I finished frame fragmentation. (May be next week.)
I think you can open a PR, that's a good idea! 😄 
Thanks for reporting that!

**Comment by jjeffcaii** [comment]
@derekam  I've changed server/client acceptor function from `fn` to boxed `Fn` in develop branch.
Now codes looks like:

```rust
    RSocketFactory::receive()
        .transport(TcpServerTransport::from(addr))
        .acceptor(Box::new(|setup, _socket| {
            info!("accept setup: {:?}", setup);
            Ok(Box::new(EchoRSocket))
            // Or you can reject setup
            // Err(From::from("SETUP_NOT_ALLOW"))
        }))
        .on_start(Box::new(|| info!("+++++++ echo server started! +++++++")))
        .serve()
        .await
```

**Comment by jjeffcaii** [comment]
Please checkout v0.5.1.
